version: "3.9"
services:
  users_db_service:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: users_password
      POSTGRES_USER: users_user
      POSTGRES_DB: users_db
    expose:
      - 5432
    networks:
      - nw

  users_web_service:
    depends_on:
      - users_db_service
    build:
      context: ../..
      dockerfile: ops/docker/users_web_service.dockerfile
    environment:
      DB_PORT: 5432
      DB_HOST: users_db_service
      DB_USERNAME: users_user
      DB_PASSWORD: users_password
      DB_NAME: users_db
    networks:
      - nw

  tweets_db_service:
    image: postgres:14.2-alpine
    environment:
      PGPORT: 5433
      POSTGRES_PASSWORD: tweets_password
      POSTGRES_USER: tweets_user
      POSTGRES_DB: tweets_db
    expose:
      - 5433
    networks:
      - nw

  tweets_web_service:
    depends_on:
      - tweets_db_service
    build:
      context: ../..
      dockerfile: ops/docker/tweets_web_service.dockerfile
    environment:
      DB_PORT: 5433
      DB_HOST: tweets_db_service
      DB_USERNAME: tweets_user
      DB_PASSWORD: tweets_password
      DB_NAME: tweets_db
    networks:
      - nw

  follows_db_service:
    image: postgres:14.2-alpine
    environment:
      PGPORT: 5434
      POSTGRES_PASSWORD: follows_password
      POSTGRES_USER: follows_user
      POSTGRES_DB: follows_db
    expose:
      - 5434
    networks:
      - nw

  follows_web_service:
    depends_on:
      - follows_db_service
    build:
      context: ../..
      dockerfile: ops/docker/follows_web_service.dockerfile
    environment:
      DB_PORT: 5434
      DB_HOST: follows_db_service
      DB_USERNAME: follows_user
      DB_PASSWORD: follows_password
      DB_NAME: follows_db
    networks:
      - nw

  nginx:
    depends_on:
      - users_web_service
      - tweets_web_service
      - follows_web_service
    build:
      context: ../..
      dockerfile: ops/docker/nginx.dockerfile
    ports:
      - 80:80
      - 443:443
    networks:
      - nw

networks:
  nw:
    name: nw
