version: "3.9"
services:
  users_db_service:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
      PGDATA: /pgtmpfs
    tmpfs:
      - /pgtmpfs

  users_web_service:
    depends_on:
      - users_db_service
    build:
      # Just to start at the src/ directory
      context: ../..
      dockerfile: ops/docker/users_web_service.dockerfile
    ports:
      - 3000:3000
    # Same values, but different names
    environment:
      DB_HOST: users_db_service
      DB_USERNAME: postgres
      DB_PASSWORD: users_password

  users_nginx:
    depends_on:
      - users_web_service
    build:
      # Just to start at the src/ directory
      context: ../..
      dockerfile: ops/docker/users_nginx.dockerfile
    ports:
      - 80:80
      - 443:443
